GET http://localhost:3000/

###

GET http://localhost:3000/json

###


POST  http://localhost:3000/product

{
    "name": "mouse"
}

###

POST  http://localhost:3000/campaign

{
	"name": "mou",
	"content": "change password",
	"emails": ["test@t.com"]
}