@url = http://localhost:3000
@url_keycloak = http://localhost:8080

GET  {{url}}/ping

###

POST  {{url}}/campaign

###

POST {{url}}/campaign/new_campaign
Authorization: Bearer {{acess_token}}

{
	"name": "mouse2",
	"content": "change password",
	"emails": ["test@t.com"]
}

###

GET {{url}}/campaign
Authorization: Bearer {{acess_token}}

###
GET {{url}}/campaign/d4g7iuqahcv0gt29e70g
Authorization: Bearer {{acess_token}}

###

# PATCH {{url}}/campaign/cancel/d4k8nt2ahcv2d16f899g
# Authorization: Bearer {{acess_token}}

###

DELETE {{url}}/campaign/delete/d4k8nt2ahcv2d16f899g
Authorization: Bearer {{acess_token}}

###

# @name token
POST 	{{url_keycloak}}/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=fernandofecci@hotmail.com&password=29522576&grant_type=password

###
@acess_token = {{token.response.body.access_token}}